---
title: "Plasmid taxonomic units (PTUs)"
author: "Liam Shaw"
date: "`r Sys.Date()`"
output: 
  html_document:
  fig_width: 12
fig_height: 8
editor_options: 
  chunk_output_type: console
---
  
  
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=TRUE, warning=FALSE, message=FALSE,
                      tidy=TRUE)
options(stringsAsFactors = FALSE)
dataDir = "../data/" # assumes being run from 'notebooks' dir
figureDir = "../output-figures/" # for figures
outputDir = "../output-data/" # for output data

# Pangenome component colours
component.colours = c("#1f78b4", "#a6cee3", "#b2df8a")
names(component.colours) = c("Core", "Non-core", "Plasmid")
```

## Libraries

```{r libraries, include=FALSE}
library(dplyr)
library(ggplot2)
library(cowplot)
library(formatR)
library(ape)
library(ggtree)
library(ggridges)
library(MCMCglmm)
library(phytools)
library(reshape2)
library(tidyr)
library(ggrepel)
```


```{r  PTU_stats}
df = read.csv(paste0(dataDir, 'redondo-salvo-2020-plasmid-DB.csv'), header=T, row.names = 1)
# Group into PTUs
ptu.df = df %>% group_by(PTU, PTU.hostrange) %>% 
  summarise(n=length(PTU.hostrange),
            median.size=median(Size))
# Plasmids that are in PTUs with host range >= II
sum(ptu.df$n[which(! ptu.df$PTU.hostrange %in% c("-", "I"))])/sum(ptu.df$n) * 100
# Proportion of PTUs with host range >= II
hostrange.ptu.table = table(ptu.df$PTU.hostrange[which(ptu.df$PTU!="-")])
sum(hostrange.ptu.table[-1])/sum(hostrange.ptu.table) * 100
```

We can compare these to statistics from the Acman dataset. 

```{r acman_stats}
acman.df = read.csv(paste0(dataDir, 'acman-plasmid-DB.csv'), header=T, row.names = 1)
acman.clique.df = acman.df %>% group_by(Clique) %>% 
  summarise(n=length(Clique),
            median.size=median(Length),
            species=length(unique(Species)))
table(acman.clique.df[which(!is.na(acman.clique.df$Clique)),]$species>1)
table(acman.clique.df[which(acman.clique.df$n>3),"species"]==1)
```
